### ISSUE TITLE
The bookmark label is not displayed in jobs on the individual job category and job types pages.

### ISSUE THREAD

**Issue by denisbaranov** [ultimatemember/um-jobboardwp#7]
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
On the individual Job Type and Job Category pages, the posts display Title - "Bookmark" without a label and cannot be bookmarked.

**Screenshots**
https://www.screencast.com/t/sgSihElmjL1w
https://www.screencast.com/t/MYdsRPYUSoV

**Do you use UM extensions?**
- [x] JobBoardWP
- [x] UM - JobBoardWP integration
- [x] UM - User Bookmarks

**Comment by nikitasinelnikov** [comment]
Fixed here [1a39d8f2357466190553413606a794be194f3e7e](https://github.com/ultimatemember/user-bookmarks/commit/1a39d8f2357466190553413606a794be194f3e7e)
